# Linter Options
options:
  merge-default-rules: true
# Rule Configuration
rules:
  no-ids: 0
  no-url-domains: 0
  no-url-protocols: 0
  nesting-depth: 0
  property-sort-order: 2
  empty-line-between-blocks: 2
  final-newline: 2
  no-trailing-whitespace: 2
  no-color-keywords: 2
  no-color-literals: 2
  space-around-operator: 2
  hex-notation: 2
  class-name-format: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
